export const surveys = [
  {
    id: "starbucks",
    name: "Starbucks",
    category: "Food & drink",
    image: "Starbucks.png",
    color: "#007042",
    title: "Your coffee ritual, rethought.",
    description: "From the first sip to the pickup counter.",
    type: "cafe",
  },
  {
    id: "apple",
    name: "Apple",
    category: "Technology",
    image: "Apple.jpg",
    color: "#161616",
    title: "A little better. Every day.",
    description: "The details that make your devices work for you.",
    type: "tech",
  },
  {
    id: "nike",
    name: "Nike",
    category: "Shopping",
    image: "nike.jpg",
    color: "#d61f18",
    title: "Made for your kind of movement.",
    description: "Fit, comfort, and what gets you moving.",
    type: "apparel",
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "Entertainment",
    image: "netflix.jpg",
    color: "#101010",
    title: "Less scrolling. More watching.",
    description: "Let’s talk about your next movie night.",
    type: "streaming",
  },
  {
    id: "target",
    name: "Target",
    category: "Shopping",
    image: "target.png",
    color: "#cc0001",
    title: "Make the everyday run better.",
    description: "The little things on your shopping list.",
    type: "retail",
  },
  {
    id: "mcdonalds",
    name: "McDonald’s",
    category: "Food & drink",
    image: "mcdonalds.png",
    color: "#d8281b",
    title: "More than your usual order.",
    description: "Fresh food, fair prices, and a smoother visit.",
    type: "food",
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "Shopping",
    image: "amazon.png",
    color: "#232f3f",
    title: "From your cart to your doorstep.",
    description: "Honest thoughts on shopping and delivery.",
    type: "ecommerce",
  },
];
// Use only supplied company artwork. These are independent sample surveys, not partnerships.
export const activeSurveys = surveys.filter((s) => s.image);
