export const surveys = [
  {
    id: "starbucks",
    name: "Starbucks",
    category: "Food & drink",
    image: "starbucks-mark.svg",
    color: "#e9f7ef",
    title: "Your coffee ritual, rethought.",
    description: "From the first sip to the pickup counter.",
    type: "cafe",
  },
  {
    id: "apple",
    name: "Apple",
    category: "Technology",
    image: "apple-mark.svg",
    color: "#edf3ff",
    title: "A little better. Every day.",
    description: "The details that make your devices work for you.",
    type: "tech",
  },
  {
    id: "nike",
    name: "Nike",
    category: "Shopping",
    image: "nike-mark.svg",
    color: "#fff0e7",
    title: "Made for your kind of movement.",
    description: "Fit, comfort, and what gets you moving.",
    type: "apparel",
  },
  {
    id: "netflix",
    name: "Netflix",
    category: "Entertainment",
    image: "netflix-mark.svg",
    color: "#ffecef",
    title: "Less scrolling. More watching.",
    description: "Let’s talk about your next movie night.",
    type: "streaming",
  },
  {
    id: "target",
    name: "Target",
    category: "Shopping",
    image: "target-mark.svg",
    color: "#fff0f0",
    title: "Make the everyday run better.",
    description: "The little things on your shopping list.",
    type: "retail",
  },
  {
    id: "mcdonalds",
    name: "McDonald’s",
    category: "Food & drink",
    image: "mcdonalds-mark.svg",
    color: "#fff4c7",
    title: "More than your usual order.",
    description: "Fresh food, fair prices, and a smoother visit.",
    type: "food",
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "Shopping",
    image: "amazon.png",
    color: "#eaf6ff",
    title: "From your cart to your doorstep.",
    description: "Honest thoughts on shopping and delivery.",
    type: "ecommerce",
  },
];
// Local artwork: original Amazon image and Simple Icons brand marks. Independent samples, not partnerships.
export const activeSurveys = surveys.filter((s) => s.image);
